force-app/main/default/objects/HealthcareProvider/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Gynecology</fullName>
            </value>
            <value>
                <fullName>Oncology</fullName>
            </value>
            <value>
                <fullName>Pediatrics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HealthcareProvider/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HealthcareProvider/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DoctorSearchAgent.cls
global class DoctorSearchAgent {
    
    @InvocableMethod(label='Fetch Available Doctors' description='Finds available Doctors')
    global static List<DoctorResponse> fetchDoctors(List<DoctorRequest> requests) {
        
        List<DoctorResponse> finalResponse = new List<DoctorResponse>();
        
        //for (DoctorSearchFilter req : requests) {
        
        List<Doctor> doctorList = new List<Doctor>();
        
        //Query HealthcareProvider object
        List<HealthcareProvider> doctors = [
            SELECT Id, Name, Department__c, Location__c, Experience__c
            FROM HealthcareProvider
            WHERE Department__c = :requests[0].filters.department
            AND Location__c = :requests[0].filters.location
            ORDER BY Experience__c DESC
            LIMIT 50
        ];
        
        // Map to output DTO
        for (HealthcareProvider d : doctors) {
            
            Doctor info = new Doctor(d.Id, d.Name, d.Department__c, d.Location__c, Integer.valueOf(d.Experience__c) );
            
            doctorList.add(info);
        }
        
		AvailableDoctor availableDoctor = new AvailableDoctor(doctorList);
        //availableDoctor.doctors = doctorList;
        
        DoctorResponse docResponse = new DoctorResponse();
        docResponse.availableDoctors = availableDoctor;
        System.debug('The Response---'+docResponse);
        System.debug('The final Response---'+JSON.serialize(docResponse));
        finalResponse.add(docResponse);
        
        System.debug('The final Response---'+finalResponse);
        System.debug('The final Response---'+JSON.serialize(finalResponse));
        
        
        return finalResponse;
    }
    
    @JsonAccess(serializable='always' deserializable='always')
    global class DoctorRequest {
        @InvocableVariable
        global DoctorRequestFilter filters;
    }
    
    @JsonAccess(serializable='always' deserializable='always')
    global class DoctorResponse {
        
        @InvocableVariable
        global AvailableDoctor availableDoctors;
    }
}